<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/ie.css', 'IE', true); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/print.css', 'print'); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/extras.css'); ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/screen.css', 'screen , projection'); ?>
        <?php $this->headTitle('Lumia - Future of Web Technology'); ?>
        
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headTitle(); ?>

    </head>
 
    
  <body>
      
     <div class="container">
        <?= $this->render('banner.phtml') ?>
         <div style="position: relative; left: 25px; top: 25px">
<?php echo $this->layout()->content; ?>
         </div>
    <?= $this->render('footer.phtml') ?>     
    </div>
    
  </body>
</html>