
<head>
    <title>Nivo Slider Demo</title>
    <link rel="stylesheet" href="<?= $this->baseURl() ?>/plugins/nivo-slider/themes/default/default.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="<?= $this->baseURl() ?>/plugins/nivo-slider/themes/pascal/pascal.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="<?= $this->baseURl() ?>/plugins/nivo-slider/themes/orman/orman.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="<?= $this->baseURl() ?>/plugins/nivo-slider/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="style.css" type="text/css" media="screen" />
</head>
<body>
    <div id="wrapper">
    
        <div class="slider-wrapper">
            <div class="ribbon"></div>
            <div id="slider" class="nivoSlider">
                <img src="<?= $this->baseURl() ?>/plugins/nivo-slider/demo/images/toystory.jpg" alt="" />
                <a href="http://dev7studios.com"><img src="<?= $this->baseURl() ?>/plugins/nivo-slider/demo/images/up.jpg" alt="" title="This is an example of a caption" /></a>
                <img src="<?= $this->baseURl() ?>/plugins/nivo-slider/demo/images/walle.jpg" alt="" data-transition="slideInLeft" />
                <img src="<?= $this->baseURl() ?>/plugins/nivo-slider/demo/images/nemo.jpg" alt="" title="#htmlcaption" />
            </div>
            <div id="htmlcaption" class="nivo-html-caption">
                <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
            </div>
        </div>

    </div>
    <script type="text/javascript" src="<?= $this->baseURl() ?>/plugins/nivo-slider/scripts/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="<?= $this->baseURl() ?>/plugins/nivo-slider/jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>
</body>
</html>